### PR TITLE
Bugfix/time in market for impersonation mode

### LINKED ISSUE #6052: Time in Market does not adapt in impersonation mode
**To Reproduce**

1. Activate _Experimental Features_ in _My Ghostfolio_
2. Impersonate a user account you have access
3. _Time in Market_ in the _Portfolio Summary_ shows my value

**Expected behavior**

_Time in Market_ should be the value of the impersonated user account

**Environment**

- Ghostfolio Version `2.222.0`
- _Experimental Features_ enabled

**Additional Context**

Integrate `dateOfFirstActivity` into `PortfolioSummary`.

### PR DESCRIPTION
**Pull request by VahantSharma**
When impersonating a user, the "Time in Market" value was still showing my own data instead of the impersonated user's.

The issue was that the component pulled `dateOfFirstActivity` from the user endpoint, which always returns the logged-in user regardless of impersonation. 

Following the suggestion in the issue, I moved `dateOfFirstActivity` into the portfolio summary response instead — that endpoint already respects impersonation, so it was a straightforward fix.

Resolves #6052

### CODE REVIEW

**Comment by dtslvr** [comment]
Could you please comment in the issue to get assigned, @VahantSharma?

File: libs/common/src/lib/interfaces/portfolio-summary.interface.ts [hunk 1]
```diff
@@ -8,6 +8,7 @@ export interface PortfolioSummary extends PortfolioPerformance {
   cash: number;
   committedFunds: number;
   dividendInBaseCurrency: number;
+  dateOfFirstActivity?: Date;
```
Comment (dtslvr) [inline libs/common/src/lib/interfaces/portfolio-summary.interface.ts]: Please move up to keep the alphabetical order

Comment (dtslvr) [inline libs/common/src/lib/interfaces/portfolio-summary.interface.ts]: Could we remove the optional flag (`?`)?

File: apps/api/src/app/portfolio/portfolio.service.ts [hunk 2]
```diff
@@ -1953,6 +1953,7 @@ export class PortfolioService {
         return ['BUY', 'SELL'].includes(type);
       }).length,
       committedFunds: committedFunds.toNumber(),
+      dateOfFirstActivity: firstOrderDate,
```
Comment (dtslvr) [inline apps/api/src/app/portfolio/portfolio.service.ts]: Move down to keep the alphabetical order

File: apps/client/src/app/components/portfolio-summary/portfolio-summary.component.ts [hunk 3]
```diff
@@ -84,10 +84,13 @@ export class GfPortfolioSummaryComponent implements OnChanges {
         this.precision = 0;
       }
 
-      if (this.user.dateOfFirstActivity) {
-        this.timeInMarket = formatDistanceToNow(this.user.dateOfFirstActivity, {
-          locale: getDateFnsLocale(this.language)
-        });
+      if (this.summary?.dateOfFirstActivity) {
```
Comment (dtslvr) [inline apps/client/src/app/components/portfolio-summary/portfolio-summary.component.ts]:
```
if (this.summary.dateOfFirstActivity) {
```
because we already check for `this.summary` above

File: apps/client/src/app/services/data.service.ts [hunk 4]
```diff
@@ -564,6 +564,11 @@ export class DataService {
             }
           }
 
+          if (response.summary?.dateOfFirstActivity) {
+            response.summary.dateOfFirstActivity = parseISO(
+              response.summary.dateOfFirstActivity
+            );
+          }
           return response;
```
Comment (dtslvr) [inline apps/client/src/app/services/data.service.ts:573]: Add line break

**Review by dtslvr — CHANGES_REQUESTED** [review]
Thanks for your contribution, @VahantSharma! 😎
I have reviewed your changes and added a few comments.

File: apps/client/src/app/services/data.service.ts (hunk 4 above)
Comment (VahantSharma) [reply apps/client/src/app/services/data.service.ts:573]: Added line break

**Comment by VahantSharma** [comment]
@dtslvr Thanks for the review! Applied all changes.
