### PR TITLE
Task/upgrade to Nx 22.3.3 and Angular 21.0

### LINKED ISSUE #5943: Upgrade to Nx 22
The goal of this issue is to upgrade this workspace to _Nx_ version `22` according to the [upgrade guide](https://github.com/ghostfolio/ghostfolio/blob/main/DEVELOPMENT.md#nx).

When I run the upgrade, I get the following error:

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: ghostfolio@2.222.0
npm error Found: @angular-devkit/build-angular@20.2.2
npm error node_modules/@angular-devkit/build-angular
npm error   dev @angular-devkit/build-angular@"20.3.9" from the root project
npm error   peerOptional @angular-devkit/build-angular@">= 18.0.0 < 21.0.0" from @nx/angular@21.5.1
npm error   node_modules/@nx/angular
npm error     dev @nx/angular@"22.0.4" from the root project
npm error   1 more (@storybook/angular)
npm error
npm error Could not resolve dependency:
npm error dev @angular-devkit/build-angular@"20.3.9" from the root project
npm error
npm error Conflicting peer dependency: @angular/compiler@20.3.9
npm error node_modules/@angular/compiler
npm error   peer @angular/compiler@"20.3.9" from @angular/localize@20.3.9
npm error   node_modules/@angular/localize
npm error     dev @angular/localize@"20.3.9" from the root project
npm error     peerOptional @angular/localize@"^20.0.0" from @angular-devkit/build-angular@20.3.9
npm error     node_modules/@angular-devkit/build-angular
npm error       dev @angular-devkit/build-angular@"20.3.9" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### PR DESCRIPTION
**Pull request by KenTandrian**
Hi @dtslvr, this PR resolves #5943. Please take a look :)

### Changes

* **Framework:** Upgraded Angular from `20.3.x` to `21.0.6`.
* **Tooling:** Upgraded Nx from `22.1.3` to `22.3.3`.
* **Ecosystem:** Bumped third-party wrappers to their Angular 21 compatible versions:
  * `ngx-markdown` (v21) and `marked` (v17)
  * `ngx-device-detector` (v11)

### Context: Migration Roadmap

*  **Stage 1:** Stabilize Tooling (Nx 22 + Angular 20.3)
*  **Stage 2:** Upgrade Ecosystem:
    * Storybook 10 + i18n
    * Jest v30
    * Markdown (`ngx-markdown` and `marked` v16)
    * Remove unused Stripe dependencies
*  **Stage 3:** Final Framework Jump (Angular 21) — *This PR*

### Key Upgrade Notes

* **Library Alignment:** Third-party libraries like `ngx-device-detector` and `ngx-markdown` were upgraded due to strict peer dependency compatibility with Angular 21, preventing `ERESOLVE` warnings during future installs.
* When running migrations, Nx automatically changed the `tsconfig.json` files of the apps and libs to use `moduleResolution: bundler`, `module: preserve` and set `lib` to have `es2022`. Therefore, I set some of them as the default in `tsconfig.base.json`.
* `CommonModule` removals were done by Nx migration.

### CODE REVIEW

File: libs/ui/src/lib/logo-carousel/logo-carousel.component.ts [hunk 1]
```diff
@@ -1,11 +1,10 @@
-import { CommonModule } from '@angular/common';
 import { ChangeDetectionStrategy, Component } from '@angular/core';
 
 import { LogoItem } from './interfaces/interfaces';
 
 @Component({
   changeDetection: ChangeDetectionStrategy.OnPush,
-  imports: [CommonModule],
+  imports: [],
```
Comment (dtslvr) [inline libs/ui/src/lib/logo-carousel/logo-carousel.component.ts]: Remove empty imports

File: package.json [hunk 2]
```diff
@@ -198,7 +198,8 @@
     "ts-node": "10.9.2",
     "tslib": "2.8.1",
     "typescript": "5.9.2",
-    "webpack-bundle-analyzer": "4.10.2"
+    "webpack-bundle-analyzer": "4.10.2",
+    "jest-util": "30.2.0"
```
Comment (dtslvr) [inline package.json]: Move up ⬆️

**Comment by KenTandrian** [comment]
@dtslvr Upgrading to Angular 21 forces some other packages to be upgraded (`ngx-markdown`, `ngx-stripe`, etc).

However, they also introduce breaking changes, especially for Stripe API. In Stripe API version `2025-09-30.clover`, the `stripe.redirectToCheckout` method is no longer supported ([docs](https://docs.stripe.com/changelog/clover/2025-09-30/remove-redirect-to-checkout)). I would prefer that to be fixed in a separate PR as it should involve some integration testing.

They are still used here:

https://github.com/ghostfolio/ghostfolio/blob/b12007b8b4b84092debb2f2c88ee24cda7606c35/apps/client/src/app/components/user-account-membership/user-account-membership.component.ts#L124

https://github.com/ghostfolio/ghostfolio/blob/b12007b8b4b84092debb2f2c88ee24cda7606c35/apps/client/src/app/pages/pricing/pricing-page.component.ts#L159

For now, I think we can only upgrade Nx to 22.3 without upgrading Angular. What do you think?

**Comment by dtslvr** [comment]
Thanks for the hint about the breaking change of `redirectToCheckout()`, @KenTandrian!
I have created a PR which eliminates `ngx-stripe`: https://github.com/ghostfolio/ghostfolio/pull/6116
