### PR TITLE
FIX #1951: select checkbox state fix for duplicates

### LINKED ISSUE #1951: [BUG] Select all activities checkbox state is not correct after import with duplicates
**Bug Description**

The select all activities checkbox state is not correct after trying to import duplicates.

**To Reproduce**

1. Import `ok-vti-buy-on-ibkr.csv`
2. Import `ok-vti-buy-on-ibkr.csv` again
3. The "Select all" checkbox is selected

**Expected behavior**

The "Select all" checkbox should not be selected, because no activity is selected

**Screenshots**

duplicate

**Environment**

- Ghostfolio Version 1.268.0

### PR DESCRIPTION
**Pull request by visrut7**

### CODE REVIEW

File: apps/client/src/app/pages/portfolio/activities/import-activities-dialog/import-activities-dialog.component.ts [hunk 1]
```diff
@@ -228,6 +229,12 @@ export class ImportActivitiesDialog implements OnDestroy {
           this.isFileSelected = true;
           this.snackBar.dismiss();
           this.changeDetectorRef.markForCheck();
+          this.activities.some((activity) => {
```
Comment (dtslvr) [inline apps/client/src/app/pages/portfolio/activities/import-activities-dialog/import-activities-dialog.component.ts:232]: What about:

```
this.isAnyActivityDuplicate = this.activities.some(({ isDuplicate }) => {
  return isDuplicate;
});
```

File: libs/ui/src/lib/activities-table/activities-table.component.ts [hunk 2]
```diff
@@ -45,6 +45,7 @@ export class ActivitiesTableComponent implements OnChanges, OnDestroy, OnInit {
   @Input() showCheckbox = false;
   @Input() showFooter = true;
   @Input() showNameColumn = true;
+  @Input() isAnyActivityDuplicate = false;
```
Comment (dtslvr) [inline libs/ui/src/lib/activities-table/activities-table.component.ts:48]: Eliminate

File: apps/client/src/app/pages/portfolio/activities/import-activities-dialog/import-activities-dialog.html [hunk 3]
```diff
@@ -71,6 +71,7 @@
         [hasPermissionToExportActivities]="false"
         [hasPermissionToFilter]="false"
         [hasPermissionToOpenDetails]="false"
+        [isAnyActivityDuplicate]="isAnyActivityDuplicate"
```
Comment (dtslvr) [inline apps/client/src/app/pages/portfolio/activities/import-activities-dialog/import-activities-dialog.html:74]: Eliminate

**Review by dtslvr — CHANGES_REQUESTED** [review]

**Review by dtslvr — APPROVED** [review]
Thanks for the refactoring @visrut7!
