### PR TITLE
Bugfix/allocate remaining percentage to unknown data in portfolio proportion chart

### LINKED ISSUE #6008: Portfolio proportion chart component shows incorrect percentage values
**Bug Description**

The [portfolio proportion chart component](https://github.com/ghostfolio/ghostfolio/tree/main/libs/ui/src/lib/portfolio-proportion-chart) shows incorrect values when data is provided in percentage format.

**To Reproduce**

1. Start _Storybook_ locally via `npm run start:storybook`
2. Open the story URL: http://localhost:4400/?path=/story/portfolio-proportion-chart--in-percentage
3. Observe the rendered value for _United States_: `88.89%`

**Expected Behavior**

Based on the _Storybook_ [data](https://github.com/ghostfolio/ghostfolio/blob/main/libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.stories.ts#L44), the value for _United States_ should be rendered as `65.15%`

**Screenshots**

Image

**Environment**

- Ghostfolio Version `2.220.0`

### PR DESCRIPTION
**Pull request by DavidReque**
hi @dtslvr this PR resolves #6008

### PR Description

Fix portfolio proportion chart showing incorrect percentage values when data is in percent format
When `isInPercent` is `true`, the chart was calculating percentages relative to the sum of all provided values instead of treating them as absolute percentages.
For example, with United States having a value of `0.6515` (65.15%) and a dataset total of ~`0.7329`, the tooltip incorrectly displayed `88.89%` instead of the expected `65.15%`.

**Solution**: If the total of the dataset is less than 100% when `isInPercent` is `true`, the remaining percentage is now allocated to `UNKNOWN_KEY` to ensure the total distribution equals 100%, making the displayed percentages accurate.

### CODE REVIEW

File: libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts [hunk 1]
```diff
@@ -193,6 +193,30 @@ export class GfPortfolioProportionChartComponent
...
+      for (const symbol in chartData) {
+        totalValue = totalValue.plus(chartData[symbol].value);
+      }
+
+      const remainingPercentage = new Big(1).minus(totalValue);
+
+      if (remainingPercentage.gt(0)) {
+        if (chartData[UNKNOWN_KEY]) {
+          chartData[UNKNOWN_KEY].value =
+            chartData[UNKNOWN_KEY].value.plus(remainingPercentage);
```
Comment (Raj-G07) [inline libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts]: - `UNKNOWN_KEY` keeps growing cumulatively every time you recalculate, which is not ideal.
- It does not automatically “shrink” if new real data is added , your UNKNOWN_KEY can become misleading.

File: libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts [hunk 2]
```diff
@@ -193,6 +193,30 @@ export class GfPortfolioProportionChartComponent
       });
     }
 
+    // If data is in percent format and total is less than 100%,
+    // allocate the remaining percentage to UNKNOWN_KEY
+    if (this.isInPercent) {
+      let totalValue = new Big(0);
+
+      for (const symbol in chartData) {
+        totalValue = totalValue.plus(chartData[symbol].value);
```
Comment (Raj-G07) [inline libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts]: - We can add condition like (symbol !== UNKNOWN_KEY) to calculate totalValue.

File: libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts [hunk 3]
```diff
@@ -193,6 +193,30 @@ export class GfPortfolioProportionChartComponent
       });
     }
 
+    // If data is in percent format and total is less than 100%,
+    // allocate the remaining percentage to UNKNOWN_KEY
+    if (this.isInPercent) {
+      let totalValue = new Big(0);
```
Comment (dtslvr) [inline libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts]: You can directly use `getSum()` from `@ghostfolio/common/helper`:
```
const totalValueInPercentage = getSum(...);
```

File: libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts [hunk 4]
```diff
@@ -193,6 +193,30 @@ export class GfPortfolioProportionChartComponent
...
+
+      for (const symbol in chartData) {
+        totalValue = totalValue.plus(chartData[symbol].value);
+      }
+
+      const remainingPercentage = new Big(1).minus(totalValue);
```
Comment (dtslvr) [inline libs/ui/src/lib/portfolio-proportion-chart/portfolio-proportion-chart.component.ts]: `const unknownValueInPercentage = new Big(1).minus(totalValueInPercentage);`
