### PR TITLE
Bugfix/adapt accounts and tags of assistant in impersonation mode

### LINKED ISSUE #2944: [BUG] Accounts in account selector of assistant do not adapt in impersonation mode
**Bug Description**

**To Reproduce**

1. Activate _Experimental Features_ in _My Ghostfolio
2. Impersonate a user account you have access
3. Accounts in the account selector of the assistant are my own accounts

**Expected behavior**

Accounts in the account selector of the assistant should be the accounts of the impersonated user account

**Screenshots**

filter-by-accounts

**Environment**

- _Experimental Features_ enabled

**Additional context**

The available accounts are set [here](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/user/user.service.ts#L88), but should be overridden in impersonation mode (can be evaluated like [this](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/app/order/order.controller.ts#L98)).

### PR DESCRIPTION
**Pull request by Anurag9977**
Closes #2944 

I have updated the controller route handler for get user to fetch accounts according to whether impersonation Id is available. Below is a screenshot of the desired output.

**Current User**
image
image

**Impersonated User**
image
image

Please review once and let me know if I missed anything. Thanks.

### CODE REVIEW

File: apps/api/src/app/user/user.controller.ts [hunk 1]
```diff
@@ -47,7 +49,8 @@ export class UserController {
     private readonly prismaService: PrismaService,
     private readonly propertyService: PropertyService,
     @Inject(REQUEST) private readonly request: RequestWithUser,
-    private readonly userService: UserService
+    private readonly userService: UserService,
+    private readonly impersonationService: ImpersonationService
```
Comment (dtslvr) [inline apps/api/src/app/user/user.controller.ts]: Move up to keep the alphabetical order ⬆️

File: apps/api/src/app/user/user.controller.ts [hunk 2]
```diff
@@ -108,10 +111,14 @@ export class UserController {
   @Get()
   @UseGuards(AuthGuard('jwt'), HasPermissionGuard)
   public async getUser(
-    @Headers('accept-language') acceptLanguage: string
+    @Headers('accept-language') acceptLanguage: string,
+    @Headers(HEADER_KEY_IMPERSONATION.toLowerCase()) impersonationId: string
   ): Promise<User> {
+    const impersonationUserId =
+      await this.impersonationService.validateImpersonationId(impersonationId);
     return this.userService.getUser(
```
Comment (dtslvr) [inline apps/api/src/app/user/user.controller.ts]: Add line break

File: apps/api/src/app/user/user.module.ts [hunk 3]
```diff
@@ -26,7 +27,8 @@ import { UserService } from './user.service';
     PrismaModule,
     PropertyModule,
     SubscriptionModule,
-    TagModule
+    TagModule,
+    ImpersonationModule
```
Comment (dtslvr) [inline apps/api/src/app/user/user.module.ts]: Move up ⬆️

File: apps/api/src/app/user/user.service.ts [hunk 4]
```diff
@@ -98,6 +98,7 @@ export class UserService {
 
   public async getUser(
     { accounts, id, permissions, settings, subscription }: UserWithSettings,
+    impersonationUserId: string | null,
```
Comment (dtslvr) [inline apps/api/src/app/user/user.service.ts]: `impersonationUserId: string,`

File: apps/api/src/app/user/user.service.ts [hunk 5]
```diff
@@ -117,7 +118,15 @@ export class UserService {
         },
         where: { userId: id }
       }),
-      this.tagService.getTagsForUser(id)
+      this.tagService.getTagsForUser(id),
+      this.prismaService.account.findMany({
```
Comment (dtslvr) [inline apps/api/src/app/user/user.service.ts]: Move up ⬆️ (after `this.prismaService.access`)

File: apps/api/src/app/user/user.service.ts [hunk 6]
```diff
@@ -117,7 +118,15 @@ export class UserService {
...
+        where: {
+          userId: impersonationUserId ?? ''
+        },
+        orderBy: {
```
Comment (dtslvr) [inline apps/api/src/app/user/user.service.ts]: Move up ⬆️

File: apps/api/src/app/user/user.service.ts [hunk 7]
```diff
@@ -117,7 +118,15 @@ export class UserService {
         },
         where: { userId: id }
       }),
-      this.tagService.getTagsForUser(id)
+      this.tagService.getTagsForUser(id),
+      this.prismaService.account.findMany({
+        where: {
+          userId: impersonationUserId ?? ''
```
Comment (dtslvr) [inline apps/api/src/app/user/user.service.ts]: `userId: impersonationUserId`

File: apps/api/src/app/user/user.service.ts [hunk 8]
```diff
@@ -126,6 +135,7 @@ export class UserService {
     let tags = userData[3].filter((tag) => {
       return tag.id !== TAG_ID_EXCLUDE_FROM_ANALYSIS;
     });
+    const impersonationAccounts = userData[4];
```
Comment (dtslvr) [inline apps/api/src/app/user/user.service.ts]: Move up ⬆️

File: apps/api/src/app/user/user.service.ts [hunk 9]
```diff
@@ -146,7 +156,7 @@ export class UserService {
     }
 
     return {
-      accounts,
+      accounts: impersonationUserId ? impersonationAccounts : accounts,
```
Comment (dtslvr) [inline apps/api/src/app/user/user.service.ts]: Move down ⬇️ (after `access`)

File: package-lock.json
Comment (dtslvr) [inline package-lock.json:1]: Please revert these changes

**Comment by Anurag9977** [comment]
@dtslvr - Thanks for the review and the suggestions. It was nice to get a quick recap on clean code practice. I have made the changes accordingly. :smile:

**Comment by Anurag9977** [comment]
@dtslvr - Hi, just wanted to follow-up on this bug fix PR. I applied the changes requested in the initial review. Please let me know if this is good to be approved. Thanks.

**Review by dtslvr — APPROVED** [review]
Thanks again and congrats on your first contribution, @Anurag9977! 🙌🏻

**Comment by Anurag9977** [comment]
> Thanks again and congrats on your first contribution, @Anurag9977! 🙌🏻

Awesome. Appreciate the opportunity! :heart:
