### PR TITLE
Task/improve usability when adding currency in market data section of admin control panel

### LINKED ISSUE #6152: [BUG] Missing UI confirmation when adding a new currency
Bug Description

When adding a new manual currency via the Administration panel, there is no visual confirmation (e.g., a success toast or notification) indicating that the currency was successfully created. The user is left unsure if the action was successful without manually searching for the new entry.

To Reproduce
    Log in as an Administrator.
    Navigate to Administration > Market Data.
    Click on the button to create a new entry (Bench / New).
    Select the tab or option to add a Currency.
    Fill in the required fields (e.g., Symbol, Name).
    Click Save (or the respective submit button).

Expected Behavior
After clicking save, a success notification (green toast message) should appear confirming that the currency has been created, and the modal should close (if applicable).

Screenshots
N/A (UI behavior issue)

Logs
N/A

Environment
    Ghostfolio Version: 2.228.0
    Cloud or Self-hosted: Self-hosted
    Experimental Features: disabled
    Browser: Chrome / Firefox
    OS: debian13 

Additional Context
This is a UX issue. The functionality itself seems to work (the currency appears in the list afterwards), but the missing feedback is confusing.

### PR DESCRIPTION
**Pull request by carlos-ds**
Closes #6152 

Also fixed a TypeError that popped up when testing the same flow: 

```
ERROR TypeError: Cannot read properties of null (reading 'length')
    at symbol-autocomplete.component.ts:124:21
```

image

### CODE REVIEW

File: apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts [hunk 1]
```diff
@@ -103,7 +103,8 @@ export class GfCreateAssetProfileDialogComponent implements OnDestroy, OnInit {
       this.dialogRef.close({
         dataSource:
           this.createAssetProfileForm.get('searchSymbol').value.dataSource,
-        symbol: this.createAssetProfileForm.get('searchSymbol').value.symbol
+        symbol: this.createAssetProfileForm.get('searchSymbol').value.symbol,
+        addAssetProfile: true
```
Comment (dtslvr) [inline apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts]: Move up ⬆️

File: apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts [hunk 2]
```diff
@@ -127,12 +128,17 @@ export class GfCreateAssetProfileDialogComponent implements OnDestroy, OnInit {
           takeUntil(this.unsubscribeSubject)
         )
         .subscribe(() => {
-          this.dialogRef.close();
+          this.dialogRef.close({
+            dataSource: this.dataSourceForExchangeRates,
+            symbol: `${DEFAULT_CURRENCY}${currency}`,
+            addAssetProfile: false
```
Comment (dtslvr) [inline apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts]: Move up ⬆️

File: apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts [hunk 3]
```diff
@@ -127,12 +128,17 @@ export class GfCreateAssetProfileDialogComponent implements OnDestroy, OnInit {
...
+          });
         });
     } else if (this.mode === 'manual') {
       this.dialogRef.close({
         dataSource: 'MANUAL',
-        symbol: `${this.ghostfolioPrefix}${this.createAssetProfileForm.get('addSymbol').value}`
+        symbol: `${this.ghostfolioPrefix}${this.createAssetProfileForm.get('addSymbol').value}`,
+        addAssetProfile: true
```
Comment (dtslvr) [inline apps/client/src/app/components/admin-market-data/create-asset-profile-dialog/create-asset-profile-dialog.component.ts]: Move up ⬆️

File: apps/client/src/app/components/admin-market-data/admin-market-data.component.ts [hunk 4]
```diff
@@ -482,31 +485,43 @@ export class GfAdminMarketDataComponent
...
-                  this.dataSource.sort = this.sort;
-                  this.isLoading = false;
-
-                  this.changeDetectorRef.markForCheck();
-                });
+                  })
+                );
             }
 
+            observable
```
Comment (dtslvr) [inline apps/client/src/app/components/admin-market-data/admin-market-data.component.ts]: Can we move this to a private function:

```
private refreshTable() {
  this.isLoading = true;
  this.changeDetectorRef.markForCheck();

  this.adminService
    .fetchAdminMarketData({ filters: this.activeFilters, take: this.pageSize })
    .pipe(takeUntil(this.unsubscribeSubject))
    .subscribe(({ marketData }) => {
      this.dataSource = new MatTableDataSource(marketData);
      this.dataSource.sort = this.sort;

      this.isLoading = false;

      this.changeDetectorRef.markForCheck();
    });
}
```

File: apps/client/src/app/components/admin-market-data/admin-market-data.component.ts [hunk 5]
```diff
@@ -482,31 +485,43 @@ export class GfAdminMarketDataComponent
         dialogRef
```
Comment (dtslvr) [inline apps/client/src/app/components/admin-market-data/admin-market-data.component.ts:482]: This is hard to read for me, what about:

```
this.dialogRef.afterClosed()
  .pipe(takeUntil(this.unsubscribeSubject))
  .subscribe((result) => {
    if (!result) {
      return;
    }
  
    const { addAssetProfile, dataSource, symbol } = result;
  
    if (addAssetProfile && dataSource && symbol) {
      this.adminService.addAssetProfile({ dataSource, symbol })
        .pipe(takeUntil(this.unsubscribeSubject))
        .subscribe(() => {
          this.refreshTable();
        });
    } else {
      this.refreshTable();
    }
  
    this.router.navigate(['.'], { relativeTo: this.route });
});
```

File: libs/ui/src/lib/symbol-autocomplete/symbol-autocomplete.component.ts [hunk 6]
```diff
@@ -121,7 +121,7 @@ export class GfSymbolAutocompleteComponent
     this.control.valueChanges
       .pipe(
         filter((query) => {
-          if (query.length === 0) {
+          if (query && query.length === 0) {
```
Comment (dtslvr) [inline libs/ui/src/lib/symbol-autocomplete/symbol-autocomplete.component.ts]:
```
if (query?.length === 0) {
```

**Review by dtslvr — CHANGES_REQUESTED** [review]
Thanks for your contribution, @carlos-ds! 😎
I have reviewed your changes and added a few comments.

**Comment by carlos-ds** [comment]
@dtslvr I've made the requested changes. Let me know if there's anything else!
